print("---------------------------------")
print("the size of dataset(飞猪):658")
print("功能识别：")
print("#precision:0.935, #recalll:0.894")
print("变化类型分类：")
print("#precision:0.912, #recall:")
print("---------------------------------")

print("---------------------------------")
print("the size of dataset(养老):54")
print("功能识别：")
print("#precision:0.214, #recalll:0.278")
print("变化类型分类：")
print("#precision:0.327")
print("---------------------------------")

print("---------------------------------")
print("the size of dataset(养老):54")
print("功能识别：")
print("#precision:0.724, #recalll:0.698")
print("变化类型分类：")
print("#precision:0.327")
print("---------------------------------")
